import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { allTools } from "../src/mcp/tools/index.js";

const lines: string[] = [
  "# MCP Tool Reference",
  "",
  "> Generated by `npm run gen:tools` from the tool registry — do not edit by hand.",
  "",
  `${allTools.length} tools.`,
  "",
];

for (const tool of allTools) {
  lines.push(`## ${tool.name}`, "", tool.description.trim(), "");
  const entries = Object.entries(tool.inputSchema);
  if (entries.length === 0) {
    lines.push("**Parameters:** none", "");
  } else {
    const params = entries.map(
      ([name, schema]) => `\`${name}${schema.isOptional() ? "?" : ""}\``,
    );
    lines.push(`**Parameters:** ${params.join(", ")}`, "");
  }
}

writeFileSync(
  fileURLToPath(new URL("../docs/tools.md", import.meta.url)),
  lines.join("\n"),
);
console.log(`docs/tools.md: ${allTools.length} tools documented.`);
